export enum LoadingState {
    LOADING = 'LOADING',
    READING_FROM_BLOCKCHAIN = 'READING_FROM_BLOCKCHAIN',
    WRITING_INTO_BLOCKCHAIN = 'WRITING_INTO_BLOCKCHAIN',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR',
    PENDING = 'PENDING'
}

export type LoadingTypeState = LoadingState.LOADING | LoadingState.READING_FROM_BLOCKCHAIN | LoadingState.WRITING_INTO_BLOCKCHAIN;
