export enum RecycleState {
    RECEIVED = 'RECEIVED',
    IN_TRANSIT = 'IN_TRANSIT',
    AT_RECYCLING_COMPANY = 'AT_RECYCLING_COMPANY',

    RECYCLED = 'RECYCLED',
    REFURBISHED = 'REFURBISHED',
    RESOLD = 'RESOLD',
    // MANUFACTIRED = 'MANUFACTIRED',
    // DELIVERED_TO_REAIL_STORE = 'DELIVERED_TO_REAIL_STORE',
    // SOLD_TO_CUSTOMER = 'SOLD_TO_CUSTOMER',

    // RECEIVED = 'ACCEPTED_AT_REAIL_STORE_FOR_RECYCLING',
    // IN_TRANSIT = 'IN_TRANSPORT_TO_RECYCLING_FACILITY',

    // RECYCLED_BURNED = 'RECYCLED-BURNED',
    // RECYCLED_BATTERY = 'RECYCLED_BATTERY',
    // RECYCLED_PRECIOUS_MATERIALS = 'RECYCLED_PRECIOUS_MATERIALS'
}
